travis:
  secure:
    BINSTAR_TOKEN: k2qJD2dtnPjD/7y1ux9l6ftly77nU1JUKIYYulCHCdgVsJGlUh6Nwz/w8WqXC9l8dQZ4CuVDDSMd12zhhy7IZ2I73EvOSgqty+k+A94buOXNkb9Z/byY+DUaJC9FgpLurDZGcTIfF4gZGiddpJMEzoTcoXhqwxOaxSb+I6+2As8oYmwvRxmLGnkoZHYci+dg5+KTRCGwQNPkS+VfCkAJuFeT23uVDFkvxAz8TBUSl2NqwqexfXG7+YVjDOSaBuZWo4Yu+xYwgZDTxZjJSCqCJhyXHgo8y/kVK2HvyjYs16y6P1ncjhjK+rgUs/7/sfD5d2t42xjXZK+ZUvrOwM//lZW295KLvJm6K/qIHqmYwzIZHD8GB8wgRbbPilQqJHgMLPlG3RD9e/ikUMaUN+yaAIw1DVInUrrmIyRagmfL8t0iubFDZ3dYPv7/hv7jZuFexyjtOykzIYiWDxo3v3uRcUqfJNNjsDapb97JwzREFzvKIH+x+sjZN9hMgjtdstoMyJLJccXKo0vnJAymQGE6MItK4/EKobcVLMHQ/6jJFet/l+qrh7bFSBd+s31Z5jl+Dvb/aUyTH2GWHdi9qx41GIMNpjgrEb4Tmrwr5QnHrS0Yq2k8mgl9U8iwsjaBx3LeGAyrj2lp3SHUfEDuzVJLRoCPHMcamy2hQbPZIULPLOU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
